# Generated by Django 4.2.1 on 2023-05-30 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dich_vu',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='static/cover_pages/'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_vote',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tarot_role',
            field=models.CharField(default='Tarot Reading and AStrology', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
