# Generated by Django 4.2.1 on 2023-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='istarot',
            field=models.BooleanField(default=False),
        ),
    ]
