# Generated by Django 4.2.1 on 2023-06-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0006_user_istarot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='start_vote',
            new_name='star_vote',
        ),
    ]
