# Generated by Django 4.2.1 on 2023-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0007_rename_start_vote_user_star_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pages/'),
        ),
    ]
