# Generated by Django 4.2.1 on 2023-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0009_alter_user_avatar_alter_user_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='star_vote',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
