# Generated by Django 4.2.1 on 2023-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0010_alter_user_star_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/avatars/default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pages/'),
        ),
    ]
