# Generated by Django 4.2.1 on 2023-06-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0011_alter_user_avatar_alter_user_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_page',
            field=models.ImageField(blank=True, default='static/img/cover_pages/default_avatar.jpg', null=True, upload_to='cover_pages/'),
        ),
    ]
