# Generated by Django 4.2.1 on 2023-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0014_alter_user_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
