# Generated by Django 4.2.1 on 2023-06-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dich_vu',
            name='content',
        ),
        migrations.AddField(
            model_name='dich_vu',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dich_vu',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dich_vu',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dich_vu',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
