# Generated by Django 4.2.1 on 2023-06-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0016_remove_dich_vu_content_dich_vu_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dich_vu',
        ),
    ]
