# Generated by Django 4.2.1 on 2023-06-11 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0017_delete_dich_vu'),
    ]

    operations = [
        migrations.CreateModel(
            name='dich_vu',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
