# Generated by Django 4.2.1 on 2023-06-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0018_dich_vu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dich_vu',
        ),
    ]
