# Generated by Django 4.2.1 on 2023-06-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0020_dich_vu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dich_vu',
            new_name='giao_dich',
        ),
    ]
