# Generated by Django 4.2.1 on 2023-06-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0025_giao_dich_is_paid_alter_giao_dich_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giao_dich',
            name='total',
        ),
    ]
