# Generated by Django 4.2.1 on 2023-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarot', '0027_alter_giao_dich_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='giao_dich',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
